# Permalinks
permalink:           pretty

# Setup
title:               Ana Campos
tagline:             PGR researcher at University of Manchester.
url:                 https://anachristinaac.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ana Campos
  url:               https://anachristinaac.github.io/
  email:             ana.campos@postgrad.manchester.ac.uk

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/jamigibbs/portfolio
google_analytics:    UA-3363703-15
github:              anachristinaac
orcid_id:	     0000-0002-7800-5640
lattes_id:	     1120877512147802

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
